import type {
  Inquiry,
  InquiryField,
  RequirementVersion,
  Opportunity,
  SupplierRfqBatch,
  SupplierRfq,
  SupplierResponse,
  SupplierComparison,
  CostCalculation,
  Quote,
  FollowUp,
} from './types';

// ─── Inquiry Fields (Extracted) ──────────────────────────────────────────────

export const inquiryFields: InquiryField[] = [
  {
    fieldKey: 'product_type',
    fieldLabel: 'Product Type',
    rawValue: 'vacuum bottles',
    normalizedValue: 'Bottle',
    unit: '',
    sourceType: 'customer_message',
    sourceMessageId: 'msg1',
    confidence: 0.95,
    status: 'confirmed',
    isRequired: true,
  },
  {
    fieldKey: 'material',
    fieldLabel: 'Material',
    rawValue: '304 stainless steel',
    normalizedValue: '304 Stainless Steel',
    unit: '',
    sourceType: 'customer_message',
    sourceMessageId: 'msg1',
    confidence: 0.98,
    status: 'confirmed',
    isRequired: true,
  },
  {
    fieldKey: 'capacity',
    fieldLabel: 'Capacity',
    rawValue: '500ml',
    normalizedValue: '500ml',
    unit: 'ml',
    sourceType: 'customer_reply',
    sourceMessageId: 'msg3',
    confidence: 1.0,
    status: 'confirmed',
    isRequired: true,
  },
  {
    fieldKey: 'quantity',
    fieldLabel: 'Quantity',
    rawValue: '10,000',
    normalizedValue: '10000',
    unit: 'pcs',
    sourceType: 'customer_message',
    sourceMessageId: 'msg1',
    confidence: 1.0,
    status: 'confirmed',
    isRequired: true,
  },
  {
    fieldKey: 'logo_method',
    fieldLabel: 'Logo Method',
    rawValue: 'silk screen logo',
    normalizedValue: 'Silk Screen',
    unit: '',
    sourceType: 'customer_reply',
    sourceMessageId: 'msg3',
    confidence: 0.95,
    status: 'confirmed',
    isRequired: false,
  },
  {
    fieldKey: 'packaging',
    fieldLabel: 'Packaging',
    rawValue: 'individual gift box',
    normalizedValue: 'Individual Gift Box',
    unit: '',
    sourceType: 'customer_reply',
    sourceMessageId: 'msg3',
    confidence: 0.97,
    status: 'confirmed',
    isRequired: false,
  },
  {
    fieldKey: 'destination',
    fieldLabel: 'Destination',
    rawValue: 'London, UK',
    normalizedValue: 'London, UK',
    unit: '',
    sourceType: 'customer_message',
    sourceMessageId: 'msg1',
    confidence: 1.0,
    status: 'confirmed',
    isRequired: true,
  },
  {
    fieldKey: 'delivery_date',
    fieldLabel: 'Delivery Date',
    rawValue: 'end of November 2026',
    normalizedValue: '2026-11-30',
    unit: '',
    sourceType: 'customer_message',
    sourceMessageId: 'msg1',
    confidence: 0.9,
    status: 'confirmed',
    isRequired: true,
  },
  {
    fieldKey: 'incoterm',
    fieldLabel: 'Incoterm',
    rawValue: 'CIF',
    normalizedValue: 'CIF',
    unit: '',
    sourceType: 'customer_message',
    sourceMessageId: 'msg1',
    confidence: 1.0,
    status: 'confirmed',
    isRequired: true,
  },
  {
    fieldKey: 'sample_required',
    fieldLabel: 'Sample Required',
    rawValue: 'yes, sample required',
    normalizedValue: 'Yes',
    unit: '',
    sourceType: 'customer_reply',
    sourceMessageId: 'msg3',
    confidence: 0.99,
    status: 'confirmed',
    isRequired: false,
  },
  {
    fieldKey: 'colour',
    fieldLabel: 'Colour',
    rawValue: '',
    normalizedValue: 'Silver',
    unit: '',
    sourceType: 'ai_inference',
    confidence: 0.7,
    status: 'assumption',
    isRequired: false,
  },
  {
    fieldKey: 'certifications',
    fieldLabel: 'Certifications Required',
    rawValue: '',
    normalizedValue: '',
    unit: '',
    sourceType: 'system_default',
    confidence: 0,
    status: 'missing',
    isRequired: false,
  },
  {
    fieldKey: 'budget',
    fieldLabel: 'Budget',
    rawValue: '',
    normalizedValue: '',
    unit: '',
    sourceType: 'system_default',
    confidence: 0,
    status: 'missing',
    isRequired: false,
  },
  {
    fieldKey: 'payment_terms',
    fieldLabel: 'Payment Terms',
    rawValue: '',
    normalizedValue: '',
    unit: '',
    sourceType: 'system_default',
    confidence: 0,
    status: 'missing',
    isRequired: false,
  },
];

// ─── Inquiry ─────────────────────────────────────────────────────────────────

export const inquiry: Inquiry = {
  id: 'inq1',
  tenantId: 't1',
  referenceNumber: 'TF-2026-0193',
  conversationId: 'conv1',
  customerId: 'c1',
  status: 'requirements_confirmed',
  categoryId: 'cat1',
  ownerId: 'u2',
  urgency: 'high',
  estimatedValue: 95000,
  currency: 'USD',
  qualificationStatus: 'qualified',
  nextAction: 'Shortlist suppliers and create RFQ batch',
  createdAt: '2026-09-15T08:23:00Z',
};

// ─── Requirement Version 1 (Confirmed) ───────────────────────────────────────

export const requirementVersion1: RequirementVersion = {
  id: 'rv1',
  inquiryId: 'inq1',
  opportunityId: 'opp1',
  versionNumber: 1,
  status: 'confirmed',
  snapshot: {
    product_type: 'Bottle',
    material: '304 Stainless Steel',
    capacity: '500ml',
    quantity: '10000',
    colour: 'Silver',
    logo_method: 'Silk Screen',
    packaging: 'Individual Gift Box',
    destination: 'London, UK',
    delivery_date: '2026-11-30',
    incoterm: 'CIF',
    sample_required: 'Yes',
    certifications: '',
    budget: '',
    payment_terms: '',
  },
  createdBy: 'u2',
  approvedBy: 'u1',
  approvedAt: '2026-09-16T14:00:00Z',
  createdAt: '2026-09-16T11:30:00Z',
};

// ─── Opportunity ──────────────────────────────────────────────────────────────

export const opportunity: Opportunity = {
  id: 'opp1',
  tenantId: 't1',
  referenceNumber: 'TF-2026-0193-OPP',
  inquiryId: 'inq1',
  customerId: 'c1',
  stage: 'comparison_ready',
  estimatedValue: 95000,
  currency: 'USD',
  targetMarginPercent: 25,
  ownerId: 'u2',
  nextAction: 'Review comparison and select supplier',
  sampleDecision: 'required',
  createdAt: '2026-09-16T14:30:00Z',
};

// ─── RFQ Batch ───────────────────────────────────────────────────────────────

export const rfqBatch: SupplierRfqBatch = {
  id: 'batch1',
  tenantId: 't1',
  referenceNumber: 'TF-BATCH-0042',
  opportunityId: 'opp1',
  requirementVersionId: 'rv1',
  status: 'sent',
  responseDeadline: '2026-09-22T17:00:00Z',
  disclosurePolicy: ['customer_name_hidden', 'quantity_visible', 'destination_visible'],
  rfqs: [
    {
      id: 'rfq1',
      batchId: 'batch1',
      supplierId: 's1',
      status: 'responded',
      outboundMessageId: 'msg5',
      responseReceivedAt: '2026-09-18T06:15:00Z',
      createdAt: '2026-09-17T09:00:00Z',
    },
    {
      id: 'rfq2',
      batchId: 'batch1',
      supplierId: 's2',
      status: 'response_incomplete',
      outboundMessageId: 'msg6',
      responseReceivedAt: '2026-09-19T03:45:00Z',
      createdAt: '2026-09-17T09:00:00Z',
    },
    {
      id: 'rfq3',
      batchId: 'batch1',
      supplierId: 's3',
      status: 'responded',
      outboundMessageId: 'msg7',
      responseReceivedAt: '2026-09-18T10:30:00Z',
      createdAt: '2026-09-17T09:00:00Z',
    },
  ],
  createdBy: 'u2',
  approvedBy: 'u1',
  approvedAt: '2026-09-17T08:30:00Z',
  createdAt: '2026-09-17T08:00:00Z',
};

// ─── Supplier Responses ──────────────────────────────────────────────────────

export const supplierResponse1: SupplierResponse = {
  id: 'resp1',
  supplierRfqId: 'rfq1',
  supplierId: 's1',
  status: 'reviewed',
  comparabilityStatus: 'comparable',
  rawResponseText: [
    'Thank you for the RFQ. We can supply 10,000 units of 500ml 304 stainless steel vacuum bottles.',
    '',
    'Pricing: USD 4.80/pc FOB Shenzhen',
    'Lead time: 25 calendar days from deposit',
    'MOQ: 1,000 pcs',
    'Payment: 30% T/T deposit, 70% before shipment',
    'Certifications: ISO 9001, FDA registered, BSCI audited',
    '',
    'Logo: Silk screen included in unit price (1 colour). Additional colours add $0.15/pc.',
    'Packaging: Individual gift box available at $0.45/pc additional.',
    'Sample: 3 samples available at unit price, freight collect.',
    '',
    'Our factory is ISO 9001 certified and FDA registered. We completed a BSCI audit in January 2026. Happy to share documentation.',
  ].join('\n'),
  normalizedData: {
    unit_price: '4.80',
    currency: 'USD',
    incoterm: 'FOB',
    lead_time_days: '25',
    moq: '1000',
    payment_terms: '30% T/T deposit, 70% before shipment',
    logo_included: 'true',
    packaging_cost: '0.45',
    sample_cost: 'unit_price',
    iso_9001: 'verified',
    fda: 'verified',
    bsci: 'documents_available',
  },
  extractionConfidence: 0.96,
  fields: [
    { fieldKey: 'unit_price', rawValue: 'USD 4.80/pc', normalizedValue: '4.80', currency: 'USD', unit: 'pc', confidence: 0.99, status: 'confirmed' },
    { fieldKey: 'incoterm', rawValue: 'FOB Shenzhen', normalizedValue: 'FOB', confidence: 0.98, status: 'confirmed' },
    { fieldKey: 'lead_time_days', rawValue: '25 calendar days', normalizedValue: '25', unit: 'days', confidence: 0.95, status: 'confirmed' },
    { fieldKey: 'moq', rawValue: '1,000 pcs', normalizedValue: '1000', unit: 'pcs', confidence: 0.98, status: 'confirmed' },
    { fieldKey: 'payment_terms', rawValue: '30% T/T deposit, 70% before shipment', normalizedValue: '30% T/T deposit, 70% before shipment', confidence: 0.97, status: 'confirmed' },
    { fieldKey: 'logo_cost', rawValue: 'Included (1 colour)', normalizedValue: '0', currency: 'USD', unit: 'pc', confidence: 0.9, status: 'confirmed' },
    { fieldKey: 'packaging_cost', rawValue: '$0.45/pc individual gift box', normalizedValue: '0.45', currency: 'USD', unit: 'pc', confidence: 0.95, status: 'confirmed' },
    { fieldKey: 'sample_available', rawValue: '3 samples at unit price', normalizedValue: 'Yes', confidence: 0.9, status: 'confirmed' },
  ],
  reviewedBy: 'u2',
  reviewedAt: '2026-09-18T09:00:00Z',
  createdAt: '2026-09-18T06:15:00Z',
};

export const supplierResponse2: SupplierResponse = {
  id: 'resp2',
  supplierRfqId: 'rfq2',
  supplierId: 's2',
  status: 'incomplete',
  comparabilityStatus: 'partially_comparable',
  rawResponseText: [
    'Hello,',
    '',
    'Thanks for the inquiry. We can make 500ml stainless steel vacuum bottles.',
    '',
    'Price: USD 5.20 per piece FOB Foshan',
    'Delivery: 30 days',
    'MOQ: 2,000 pieces',
    '',
    'We have ISO 9001 certification. Please let us know if you need any other information.',
    '',
    'Best regards,',
    'Li Chen',
  ].join('\n'),
  normalizedData: {
    unit_price: '5.20',
    currency: 'USD',
    incoterm: 'FOB',
    lead_time_days: '30',
    moq: '2000',
  },
  extractionConfidence: 0.62,
  fields: [
    { fieldKey: 'unit_price', rawValue: 'USD 5.20 per piece', normalizedValue: '5.20', currency: 'USD', unit: 'pc', confidence: 0.95, status: 'confirmed' },
    { fieldKey: 'incoterm', rawValue: 'FOB Foshan', normalizedValue: 'FOB', confidence: 0.93, status: 'confirmed' },
    { fieldKey: 'lead_time_days', rawValue: '30 days', normalizedValue: '30', unit: 'days', confidence: 0.9, status: 'confirmed' },
    { fieldKey: 'moq', rawValue: '2,000 pieces', normalizedValue: '2000', unit: 'pcs', confidence: 0.92, status: 'confirmed' },
  ],
  createdAt: '2026-09-19T03:45:00Z',
};

export const supplierResponse3: SupplierResponse = {
  id: 'resp3',
  supplierRfqId: 'rfq3',
  supplierId: 's3',
  status: 'reviewed',
  comparabilityStatus: 'partially_comparable',
  rawResponseText: [
    'Dear TradeFlow Team,',
    '',
    'We are happy to quote for your vacuum bottle project.',
    '',
    'Unit Price: USD 3.90/pc FOB Yiwu',
    'Lead Time: 20 days after confirmation',
    'MOQ: 500 pcs',
    'Payment: 100% T/T in advance (first order)',
    '',
    'We hold ISO 9001, FDA, and BSCI certifications. Silk screen and laser engraving available. Gift box packaging at $0.35/pc.',
    '',
    'We can send samples within 3 days. Sample cost $5/pc, refundable on order.',
    '',
    'Looking forward to working with you.',
    '',
    'Zhou Wei',
  ].join('\n'),
  normalizedData: {
    unit_price: '3.90',
    currency: 'USD',
    incoterm: 'FOB',
    lead_time_days: '20',
    moq: '500',
    payment_terms: '100% T/T in advance (first order)',
    packaging_cost: '0.35',
  },
  extractionConfidence: 0.88,
  fields: [
    { fieldKey: 'unit_price', rawValue: 'USD 3.90/pc', normalizedValue: '3.90', currency: 'USD', unit: 'pc', confidence: 0.97, status: 'confirmed' },
    { fieldKey: 'incoterm', rawValue: 'FOB Yiwu', normalizedValue: 'FOB', confidence: 0.95, status: 'confirmed' },
    { fieldKey: 'lead_time_days', rawValue: '20 days', normalizedValue: '20', unit: 'days', confidence: 0.9, status: 'confirmed' },
    { fieldKey: 'moq', rawValue: '500 pcs', normalizedValue: '500', unit: 'pcs', confidence: 0.93, status: 'confirmed' },
    { fieldKey: 'payment_terms', rawValue: '100% T/T in advance', normalizedValue: '100% T/T in advance', confidence: 0.85, status: 'confirmed' },
    { fieldKey: 'packaging_cost', rawValue: '$0.35/pc gift box', normalizedValue: '0.35', currency: 'USD', unit: 'pc', confidence: 0.9, status: 'confirmed' },
    { fieldKey: 'sample_available', rawValue: 'Samples within 3 days, $5/pc refundable', normalizedValue: 'Yes', confidence: 0.85, status: 'confirmed' },
  ],
  reviewedBy: 'u2',
  reviewedAt: '2026-09-18T14:00:00Z',
  createdAt: '2026-09-18T10:30:00Z',
};

// ─── Comparison ──────────────────────────────────────────────────────────────

export const comparison: SupplierComparison = {
  id: 'comp1',
  opportunityId: 'opp1',
  requirementVersionId: 'rv1',
  status: 'ready_for_review',
  recommendation: {
    recommendedSupplierId: 's1',
    alternativeSupplierId: 's3',
    reasons: [
      'Shenzhen Steel Works: best balance of verified quality, competitive pricing, and reliable lead time',
      'Strongest verification status (site_visit_completed, ISO+FDA verified)',
      'Full response with all cost components disclosed',
    ],
    risks: [
      'Yiwu Drinkware Factory offers 19% lower price but is unverified (public_lead only)',
      'Guangdong response incomplete — packaging cost not provided, making full comparison impossible',
    ],
    missingInformation: [
      'Guangdong packaging cost per unit',
      'Guangdong payment terms',
      'Guangdong sample availability',
    ],
  },
  flags: [
    {
      type: 'pricing_anomaly',
      description: 'Yiwu quote ($3.90 FOB) is 19% below Shenzhen ($4.80 FOB) — may indicate lower material grade or hidden costs',
      severity: 'warning',
    },
    {
      type: 'supplier_risk',
      description: 'Yiwu Drinkware Factory is a new supplier with no verification history — public_lead only',
      severity: 'warning',
    },
    {
      type: 'incomplete_response',
      description: 'Guangdong Metal Products response missing packaging cost, payment terms, and sample info',
      severity: 'error',
    },
    {
      type: 'grade_variance',
      description: 'All three quotes are FOB but from different factory tiers — Guangdong may use lower-grade 201 steel despite claiming 304',
      severity: 'info',
    },
  ],
  selectedSupplierId: 's1',
  createdAt: '2026-09-19T10:00:00Z',
};

// ─── Cost Calculation ────────────────────────────────────────────────────────

export const costCalculation: CostCalculation = {
  id: 'calc1',
  opportunityId: 'opp1',
  comparisonId: 'comp1',
  formulaVersion: 'v2.1',
  currency: 'USD',
  inputs: [
    {
      key: 'quantity',
      label: 'Order Quantity',
      amount: 10000,
      source: 'supplier_quote',
      sourceDetail: 'Customer requirement — confirmed',
      confirmed: true,
    },
    {
      key: 'supplierUnitCost',
      label: 'Supplier Unit Cost (FOB)',
      amount: 4.80,
      source: 'supplier_quote',
      sourceDetail: 'Shenzhen Steel Works — RFQ response',
      confirmed: true,
    },
    {
      key: 'packagingCost',
      label: 'Packaging (Individual Gift Box)',
      amount: 0.45,
      source: 'user_entered',
      sourceDetail: 'Estimated from Shenzhen quote — $0.45/pc',
      confirmed: false,
    },
    {
      key: 'toolingCost',
      label: 'Tooling / Mould',
      amount: 0,
      source: 'supplier_quote',
      sourceDetail: 'No tooling required — standard bottle',
      confirmed: true,
    },
    {
      key: 'inspectionCost',
      label: 'Pre-Shipment Inspection',
      amount: 800,
      source: 'system_default',
      sourceDetail: 'Standard inspection fee for 10k units',
      confirmed: false,
    },
    {
      key: 'freightCost',
      label: 'Freight (CIF London)',
      amount: 2200,
      source: 'external_estimate',
      sourceDetail: 'Freight forwarder quote — 20ft container Shenzhen to London',
      confirmed: false,
    },
    {
      key: 'insuranceCost',
      label: 'Marine Insurance',
      amount: 150,
      source: 'system_default',
      sourceDetail: 'Standard 0.25% of cargo value',
      confirmed: false,
    },
    {
      key: 'dutyCost',
      label: 'Import Duty',
      amount: 0,
      source: 'system_default',
      sourceDetail: 'Origin: CN, Destination: UK — standard duty applies at import',
      confirmed: false,
    },
    {
      key: 'handlingCost',
      label: 'Port Handling & Documentation',
      amount: 300,
      source: 'user_entered',
      sourceDetail: 'Estimated — port handling, customs docs',
      confirmed: false,
    },
  ],
  outputs: {
    supplierCost: 52500,
    subtotalBeforeContingency: 55950,
    contingencyCost: 2797.5,
    totalCost: 58747.5,
    grossProfit: 36252.5,
    customerPrice: 95000,
    grossMarginPercent: 38.16,
    costPerUnit: 5.87475,
    pricePerUnit: 9.5,
  },
  warnings: [
    'Packaging cost ($0.45/pc) is an estimate — confirmed with Shenzhen but not yet finalised',
    'Freight cost ($2,200) based on forwarder estimate — subject to booking confirmation',
    'Contingency at 5% — consider increasing to 10% for new supplier risk',
    'Insurance and duty amounts are system defaults — verify with customs broker',
  ],
  createdBy: 'u2',
  createdAt: '2026-09-19T11:30:00Z',
};

// ─── Quote ──────────────────────────────────────────────────────────────────

export const quote: Quote = {
  id: 'q1',
  tenantId: 't1',
  referenceNumber: 'TF-Q-2026-0193',
  opportunityId: 'opp1',
  comparisonId: 'comp1',
  costCalculationId: 'calc1',
  status: 'sent',
  customerPrice: 95000,
  currency: 'USD',
  validUntil: '2026-10-19T23:59:59Z',
  internalView: {
    supplierId: 's1',
    supplierCost: 52500,
    marginPercent: 44.74,
    costBreakdown: [
      { key: 'unit_cost', label: 'Unit Cost (10,000 x $4.80)', amount: 48000, source: 'supplier_quote', sourceDetail: 'Shenzhen Steel Works', confirmed: true },
      { key: 'packaging', label: 'Packaging (10,000 x $0.45)', amount: 4500, source: 'user_entered', sourceDetail: 'Estimated', confirmed: false },
      { key: 'inspection', label: 'Pre-Shipment Inspection', amount: 800, source: 'system_default', sourceDetail: 'Standard', confirmed: false },
      { key: 'freight', label: 'Freight (CIF London)', amount: 2200, source: 'external_estimate', sourceDetail: 'Forwarder quote', confirmed: false },
      { key: 'insurance', label: 'Marine Insurance', amount: 150, source: 'system_default', sourceDetail: '0.25% of cargo', confirmed: false },
      { key: 'handling', label: 'Port Handling', amount: 300, source: 'user_entered', sourceDetail: 'Estimated', confirmed: false },
    ],
    assumptions: [
      'Colour: Silver (assumed — not confirmed by customer)',
      'Logo: 1-colour silk screen (included in unit price)',
      'Payment: 30/70 T/T with Shenzhen',
      'No tooling required — standard vacuum bottle',
    ],
    warnings: [
      'Packaging cost is an estimate pending final confirmation',
      'Freight quote valid for 14 days only',
      'Yiwu alternative is 19% cheaper but carries significant quality risk',
    ],
  },
  customerView: {
    productName: '500ml 304 Stainless Steel Vacuum Bottle — Silver',
    quantity: 10000,
    unitPrice: 9.5,
    totalPrice: 95000,
    deliveryEstimate: '30 November 2026',
    incoterm: 'CIF London',
    paymentTerms: '50% on order confirmation, 50% on delivery',
    validityDate: '19 October 2026',
    notes: 'Sample available on request. Lead time: 25 working days from deposit.',
    exclusions: [
      'Import duties and VAT (customer responsibility at destination)',
      'Storage or onward distribution beyond London port',
      'Artwork origination charges (if new logo artwork required)',
    ],
  },
  auditTrail: [
    {
      action: 'created',
      actor: 'u2',
      timestamp: '2026-09-19T12:00:00Z',
      details: 'Quote draft created from cost calculation calc1',
    },
    {
      action: 'submitted_for_approval',
      actor: 'u2',
      timestamp: '2026-09-19T12:15:00Z',
      details: 'Submitted to James Mitchell for approval',
    },
    {
      action: 'approved',
      actor: 'u1',
      timestamp: '2026-09-19T14:30:00Z',
      details: 'Approved — margin acceptable. Note: flag packaging estimate for final confirmation.',
    },
    {
      action: 'sent',
      actor: 'u2',
      timestamp: '2026-09-19T15:00:00Z',
      details: 'Quote sent to sarah.chen@globalbottling.co.uk',
    },
  ],
  createdBy: 'u2',
  approvedBy: 'u1',
  approvedAt: '2026-09-19T14:30:00Z',
  sentAt: '2026-09-19T15:00:00Z',
  createdAt: '2026-09-19T12:00:00Z',
};

// ─── Follow-up Sequence ─────────────────────────────────────────────────────

export const followUp: FollowUp = {
  id: 'fu1',
  tenantId: 't1',
  opportunityId: 'opp1',
  quoteId: 'q1',
  status: 'active',
  currentStep: 1,
  nextDueAt: '2026-09-22T09:00:00Z',
  steps: [
    {
      day: 0,
      label: 'Quote Sent',
      action: 'Email quote to customer with personalised cover note',
      status: 'completed',
      sentAt: '2026-09-19T15:00:00Z',
    },
    {
      day: 3,
      label: 'Check-in',
      action: 'Follow up on quote — ask if they have questions or need modifications',
      status: 'pending',
    },
    {
      day: 7,
      label: 'Value Reinforcement',
      action: 'Share relevant case study or factory certification docs to build confidence',
      status: 'pending',
    },
    {
      day: 14,
      label: 'Urgency Reminder',
      action: 'Remind quote expiry approaching — offer to extend or discuss terms',
      status: 'pending',
    },
  ],
  createdAt: '2026-09-19T15:05:00Z',
};
