import type {
  Tenant,
  User,
  Customer,
  Category,
  Supplier,
} from './types';

// ─── Tenant ──────────────────────────────────────────────────────────────────

export const tenant: Tenant = {
  id: 't1',
  name: 'TradeFlow Sourcing',
  legalName: 'TradeFlow Sourcing Ltd',
  defaultCurrency: 'USD',
  defaultTimezone: 'Europe/London',
  countryOrRegion: 'GB',
  defaultMarginPercent: 25,
  minimumMarginPercent: 15,
};

// ─── Users ───────────────────────────────────────────────────────────────────

export const users: User[] = [
  {
    id: 'u1',
    tenantId: 't1',
    name: 'James Mitchell',
    email: 'james@tradeflow-sourcing.com',
    role: 'owner',
    locale: 'en-GB',
    isActive: true,
  },
  {
    id: 'u2',
    tenantId: 't1',
    name: 'Priya Sharma',
    email: 'priya@tradeflow-sourcing.com',
    role: 'manager',
    locale: 'en-GB',
    isActive: true,
  },
  {
    id: 'u3',
    tenantId: 't1',
    name: 'Liam O\'Brien',
    email: 'liam@tradeflow-sourcing.com',
    role: 'operator',
    locale: 'en-GB',
    isActive: true,
  },
];

// ─── Customers ───────────────────────────────────────────────────────────────

export const customers: Customer[] = [
  {
    id: 'c1',
    tenantId: 't1',
    companyName: 'Global Bottling Ltd',
    contactName: 'Sarah Chen',
    email: 'sarah.chen@globalbottling.co.uk',
    phone: '+44 20 7946 0958',
    country: 'GB',
    notes: 'Repeat buyer — premium drinkware line. Prefers CIF to London. Previous orders: reusable tumblers (Q1 2026), glass bottles (Q3 2025). Decision-maker for procurement.',
    source: 'website_form',
    createdAt: '2025-08-12T09:15:00Z',
  },
  {
    id: 'c2',
    tenantId: 't1',
    companyName: 'AquaPure GmbH',
    contactName: 'Hans Müller',
    email: 'hans@aquapure.de',
    phone: '+49 30 12345678',
    country: 'DE',
    notes: 'German distributor. Interested in BPA-free range.',
    source: 'trade_show',
    createdAt: '2026-02-10T14:30:00Z',
  },
  {
    id: 'c3',
    tenantId: 't1',
    companyName: 'Pacific Drinks Pty',
    contactName: 'Emily Wong',
    email: 'emily@pacificdrinks.com.au',
    phone: '+61 2 9876 5432',
    country: 'AU',
    notes: 'APAC distributor. High-volume buyer.',
    source: 'referral',
    createdAt: '2025-11-03T07:45:00Z',
  },
];

// ─── Categories ──────────────────────────────────────────────────────────────

export const categories: Category[] = [
  {
    id: 'cat1',
    tenantId: 't1',
    name: 'Drinkware — Bottles',
    slug: 'drinkware-bottles',
    fields: [
      {
        key: 'product_type',
        label: 'Product Type',
        type: 'select',
        required: true,
        options: ['Bottle', 'Tumbler', 'Flask', 'Jug', 'Cup'],
      },
      {
        key: 'material',
        label: 'Material',
        type: 'select',
        required: true,
        options: ['304 Stainless Steel', '316 Stainless Steel', 'Tritan Plastic', 'Borosilicate Glass', 'BPA-Free Plastic'],
      },
      {
        key: 'capacity',
        label: 'Capacity',
        type: 'text',
        required: true,
        unit: 'ml',
        examples: ['350ml', '500ml', '750ml', '1L'],
      },
      {
        key: 'quantity',
        label: 'Quantity',
        type: 'number',
        required: true,
        unit: 'pcs',
      },
      {
        key: 'colour',
        label: 'Colour',
        type: 'text',
        required: false,
        examples: ['Silver', 'Black', 'Rose Gold', 'Navy Blue'],
      },
      {
        key: 'logo_method',
        label: 'Logo Method',
        type: 'select',
        required: false,
        options: ['Silk Screen', 'Laser Engraving', 'Pad Printing', 'Heat Transfer', 'None'],
      },
      {
        key: 'packaging',
        label: 'Packaging',
        type: 'select',
        required: false,
        options: ['Individual Gift Box', 'Bulk (no individual box)', 'Custom Window Box', 'Poly Bag'],
      },
      {
        key: 'sample_required',
        label: 'Sample Required',
        type: 'boolean',
        required: false,
      },
      {
        key: 'certifications',
        label: 'Certifications Required',
        type: 'select',
        required: false,
        options: ['FDA', 'LFGB', 'BPA-Free', 'ISO 9001', 'BSCI'],
      },
      {
        key: 'destination',
        label: 'Destination',
        type: 'text',
        required: true,
      },
      {
        key: 'delivery_date',
        label: 'Delivery Date',
        type: 'text',
        required: true,
      },
      {
        key: 'incoterm',
        label: 'Incoterm',
        type: 'select',
        required: true,
        options: ['FOB', 'CIF', 'DDP', 'EXW'],
      },
    ],
    active: true,
  },
  {
    id: 'cat2',
    tenantId: 't1',
    name: 'Drinkware — Tumblers',
    slug: 'drinkware-tumblers',
    fields: [
      {
        key: 'product_type',
        label: 'Product Type',
        type: 'select',
        required: true,
        options: ['Tumbler', 'Insulated Tumbler', 'Travel Mug'],
      },
      {
        key: 'material',
        label: 'Material',
        type: 'select',
        required: true,
        options: ['304 Stainless Steel', 'Tritan Plastic', 'Borosilicate Glass'],
      },
      {
        key: 'capacity',
        label: 'Capacity',
        type: 'text',
        required: true,
        unit: 'ml',
        examples: ['350ml', '450ml', '600ml'],
      },
      {
        key: 'quantity',
        label: 'Quantity',
        type: 'number',
        required: true,
        unit: 'pcs',
      },
    ],
    active: true,
  },
];

// ─── Suppliers ───────────────────────────────────────────────────────────────

export const suppliers: Supplier[] = [
  {
    id: 's1',
    tenantId: 't1',
    name: 'Shenzhen Steel Works',
    legalName: 'Shenzhen Steel Works Manufacturing Co., Ltd',
    supplierType: 'existing',
    country: 'CN',
    city: 'Shenzhen',
    contactName: 'Wei Zhang',
    email: 'wei.zhang@szsteelworks.cn',
    phone: '+86 755 2345 6789',
    website: 'https://szsteelworks.cn',
    specialties: ['stainless steel bottles', 'vacuum flasks', 'insulated drinkware', 'custom metal fabrication'],
    verificationLevel: 'site_visit_completed',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-15T10:00:00Z',
    internalRating: 4.5,
    notes: 'Our most reliable supplier for stainless steel drinkware. Annual capacity 5M+ units. On-site audit completed March 2026. Dedicated English-speaking sales team. Responds within 24 hours.',
    evidence: [
      {
        id: 'ev1',
        sourceType: 'site_visit',
        sourceTitle: 'On-site audit report — March 2026',
        sourceDate: '2026-03-15',
        claimText: 'Factory audit passed. Capacity confirmed at 200,000 units/month. Clean room for food-grade production.',
        verificationStatus: 'verified',
        reviewedBy: 'u1',
        reviewedAt: '2026-03-20T11:00:00Z',
      },
      {
        id: 'ev2',
        sourceType: 'certification',
        sourceTitle: 'ISO 9001:2015 Certificate',
        sourceDate: '2025-06-01',
        claimText: 'ISO 9001:2015 quality management certification',
        verificationStatus: 'verified',
        reviewedBy: 'u2',
        reviewedAt: '2025-07-10T09:00:00Z',
      },
    ],
    certifications: [
      { name: 'ISO 9001', status: 'verified' },
      { name: 'FDA', status: 'verified' },
      { name: 'BSCI', status: 'documents_available' },
      { name: 'LFGB', status: 'documents_available' },
    ],
    moq: 1000,
    leadTimeDays: 25,
    createdAt: '2024-09-01T08:00:00Z',
  },
  {
    id: 's2',
    tenantId: 't1',
    name: 'Guangdong Metal Products',
    legalName: 'Guangdong Metal Products Co., Ltd',
    supplierType: 'existing',
    country: 'CN',
    city: 'Foshan',
    contactName: 'Li Chen',
    email: 'li.chen@gdmetal.cn',
    phone: '+86 757 8765 4321',
    website: 'https://gdmetal.cn',
    specialties: ['stainless steel kitchenware', 'metal drinkware', 'custom stamping'],
    verificationLevel: 'documents_received',
    verificationStatus: 'unverified',
    internalRating: 3.2,
    notes: 'Newer relationship. Good pricing but slower responses. Documents received but not yet independently verified. FDA status unclear — they claim it but no certificate provided.',
    evidence: [
      {
        id: 'ev3',
        sourceType: 'supplier_submission',
        sourceTitle: 'ISO 9001 claim — unverified',
        sourceDate: '2026-01-20',
        claimText: 'Claims ISO 9001 certification — documents requested but not yet received.',
        verificationStatus: 'unverified',
      },
    ],
    certifications: [
      { name: 'ISO 9001', status: 'claimed' },
      { name: 'FDA', status: 'not_confirmed' },
      { name: 'BSCI', status: 'claimed' },
    ],
    moq: 2000,
    leadTimeDays: 30,
    createdAt: '2025-11-15T10:00:00Z',
  },
  {
    id: 's3',
    tenantId: 't1',
    name: 'Yiwu Drinkware Factory',
    legalName: 'Yiwu Drinkware Factory',
    supplierType: 'new',
    country: 'CN',
    city: 'Yiwu',
    contactName: 'Zhou Wei',
    email: 'zhouwei@yiwudrink.com',
    phone: '+86 579 8523 4567',
    website: 'https://yiwudrink.com',
    specialties: ['custom drinkware', 'promotional bottles', 'small batch production'],
    verificationLevel: 'public_lead',
    verificationStatus: 'unverified',
    internalRating: 0,
    notes: 'New supplier found via Alibaba. Very competitive pricing and low MOQ. Claims all major certifications but nothing verified. Needs thorough vetting before production order.',
    evidence: [],
    certifications: [
      { name: 'ISO 9001', status: 'claimed' },
      { name: 'FDA', status: 'claimed' },
      { name: 'BSCI', status: 'claimed' },
    ],
    moq: 500,
    leadTimeDays: 20,
    createdAt: '2026-08-01T12:00:00Z',
  },
];
